
/****** Object:  Index [IX_Publisher_Title_Author]    Script Date: 28-12-2023 10:27:10 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_BookId_ContentOrder] ON [dbo].[BooksContents]
(
	[BookId] ASC,
	[ContentOrder] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO